name: Deploy Next.js App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Copy secrets
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL:-default }}" >> .env
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID:-default }}" >> .env
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET:-default }}" >> .env
        echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET:-default }}" >> .env
        echo "NODE_ENV=${{ secrets.NODE_ENV:-default }}" >> .env

    - name: Build
      run: npm run build

    - name: Start application
      run: |
        pm2 delete hema-nextjs-client || true
        pm2 start npm --name "hema-nextjs-client" -- start