name: Deploy Next.js App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Copy secrets
      run: |
        echo "${{secrets.NEXT_ENV_FILE}}" > .env

    - name: Build
      run: npm run build